const filterType = {
    Amaro: "amaro",
    Brannan: "brannan",
    Earlybird: "earlybird",
    F1977: "f1977",
    Hefe: "hefe",
    Hudson: "hudson",
    Inkwell: "inkwell",
    Lokofi: "lokofi",
    LordKelvin: "lordkelvin",
    Nashville: "nashville",
    Negative: "negative",
    Normal: "normal",
    Rise: "rise",
    Saturate: "saturate",
    Sepia: "sepia",
    Sharpen: "sharpen",
    Sierra: "sierra",
    Sutro: "sutro",
    Temperature: "temperature",
    Toaster: "toaster",
    Valencia: "velencia",
    Walden: "walden",
    XproII: "xproII",
    Temperature: "temperature",
    Hue: "hue",
    Negative: "negative",
    Sharpen: "sharpen",
    Saturate: "saturate",
    Sepia: "sepia",
};

export default filterType;
